pipeline:
  build:
    image: plugins/docker
    registry: docker.example.com
    repo: docker.example.com/react-app
    username:
      from_secret: username
    password:
      from_secret: password
    tags:
      - 1.0.0
      - 1.0
      - latest
  ssh:
    image: appleboy/drone-ssh
    host: example.com
    username:
      from_secret: ssh_user
    password:
      from_secret: ssh_password
    port: 22
    command_timeout: 2m
    script:
      - cd /var/opt/react-app/ && ./react-app.sh
